food = ['apple', 'banana', 'cherry']
print(food)
print(food[0])
print(food[1])
print(food[2])
food[0] = 'peach'
print(food)
food.append('coconut')
print(food)
# food.extend('string')
food.extend(['string', 2, True])
print(food)
food.remove('string')
# food.remove('test')
print(food)
print('cherry' in food)
print('test' in food)
print('test' not in food)
print(food[:2])
print(food[2:])
print(food[2::2])